<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '11',
    'typeid' => '0',
    'title' => '原标题：“平语”近人——习近平谈把握经济新常态“大逻',
    'style' => '',
    'thumb' => '',
    'keywords' => '习近平 平语 近人',
    'description' => '[编前语]习近平总书记提出我国经济发展进入新常态的论断迄今已逾一年。一年多的经济发展进程，是以习近平同志为核心的党中央领导全国人民适   ',
    'posids' => '0',
    'url' => 'http://localhost/PC/index.php?m=content&c=index&a=show&catid=11&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1482317605',
    'updatetime' => '1482317700',
    'hitsid' => 'c-1-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '11',
    'typeid' => '0',
    'title' => '如何理解中国经济呈现新常态？',
    'style' => '',
    'thumb' => '',
    'keywords' => '常态 中国经济',
    'description' => '当前，我国经济发展呈现速度变化、结构优化、动力转换三大特点。适应新常态、把握新常态、引领新常态，是当前和今后一个时期我国经济发展的   ',
    'posids' => '0',
    'url' => 'http://localhost/PC/index.php?m=content&c=index&a=show&catid=11&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1482317703',
    'updatetime' => '1482317714',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '11',
    'typeid' => '0',
    'title' => '如何准确认识经济新常态？',
    'style' => '',
    'thumb' => '',
    'keywords' => '常态 经济',
    'description' => '从时间和空间审视　　全面认识和把握新常态，需要从时间和空间大角度审视我国发展。从时间上看，我国发展经历了由盛到衰再到盛的几个大时期   ',
    'posids' => '0',
    'url' => 'http://localhost/PC/index.php?m=content&c=index&a=show&catid=11&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1482317716',
    'updatetime' => '1482317726',
    'hitsid' => 'c-1-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '11',
    'typeid' => '0',
    'title' => '在认识新常态上，要准确把握内涵，注意克服几种倾向。',
    'style' => '',
    'thumb' => '',
    'keywords' => '常态 内涵 倾向',
    'description' => '其一，新常态不是一个事件，不要用好或坏来判断。有人问，新常态是一个好状态还是一个坏状态？这种问法是不科学的。新常态是一个客观状态，   ',
    'posids' => '0',
    'url' => 'http://localhost/PC/index.php?m=content&c=index&a=show&catid=11&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1482317728',
    'updatetime' => '1482317738',
    'hitsid' => 'c-1-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '11',
    'typeid' => '0',
    'title' => '坚持以经济建设为中心',
    'style' => '',
    'thumb' => '',
    'keywords' => '以经济',
    'description' => '面对中国经济发展进入新常态、世界经济发展进入转型期、世界科技发展酝酿新突破的发展格局，我们要坚持以经济建设为中心，坚持以新发展理念   ',
    'posids' => '0',
    'url' => 'http://localhost/PC/index.php?m=content&c=index&a=show&catid=11&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1482317740',
    'updatetime' => '1482317749',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '11',
    'typeid' => '0',
    'title' => '坚持稳中求进工作总基调',
    'style' => '',
    'thumb' => '',
    'keywords' => '基调',
    'description' => '　要坚持稳中求进工作总基调，主动适应经济发展新常态，坚持以提高经济发展质量和效益为中心，狠抓工作落实。要保持宏观政策基本稳定，加强   ',
    'posids' => '0',
    'url' => 'http://localhost/PC/index.php?m=content&c=index&a=show&catid=11&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1482317751',
    'updatetime' => '1482317762',
    'hitsid' => 'c-1-6',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '11',
    'typeid' => '0',
    'title' => '　坚持以提高经济发展质量和效益为中心',
    'style' => '',
    'thumb' => '',
    'keywords' => '经济发展 效益 质量',
    'description' => '中国将主动适应和引领经济发展新常态，坚持以提高经济发展质量和效益为中心，把转方式调结构放到更加重要位置，更加扎实地推进经济发展，更   ',
    'posids' => '0',
    'url' => 'http://localhost/PC/index.php?m=content&c=index&a=show&catid=11&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1482317764',
    'updatetime' => '1482317775',
    'hitsid' => 'c-1-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>