<?php
return array (
  8 => 
  array (
    'id' => '8',
    'catid' => '19',
    'typeid' => '0',
    'title' => '[愿意“许身报国”]',
    'style' => '',
    'thumb' => '',
    'keywords' => '许身',
    'description' => '原标题：潘基文发出参选总统最强信号　　新华社北京12月21日新媒体专电（记者张旌）联合国秘书长潘基文20日接受媒体记者采访时说，如果他过   ',
    'posids' => '0',
    'url' => 'http://localhost/PC/index.php?m=content&c=index&a=show&catid=19&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1482321423',
    'updatetime' => '1482321479',
    'hitsid' => 'c-1-8',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '19',
    'typeid' => '0',
    'title' => '[与朴槿惠“划界”]',
    'style' => '',
    'thumb' => '',
    'keywords' => '朴槿惠',
    'description' => '潘基文一直以来很少就韩国国内事务表态，称自己要把主要精力放在联合国相关事务上。但在最近一场活动中，他对韩国总统朴槿惠亲信干政丑闻予   ',
    'posids' => '0',
    'url' => 'http://localhost/PC/index.php?m=content&c=index&a=show&catid=19&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1482321481',
    'updatetime' => '1482321523',
    'hitsid' => 'c-1-9',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '19',
    'typeid' => '0',
    'title' => '北京发布网约车管理细则',
    'style' => '',
    'thumb' => '',
    'keywords' => '北京 细则',
    'description' => '继今年7月28日交通运输部联合多部门公布《网络预约出租汽车经营服务管理暂行办法》后，经过几个月的研究和制定，今天，北京市《网约预约出   ',
    'posids' => '0',
    'url' => 'http://localhost/PC/index.php?m=content&c=index&a=show&catid=19&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1482321525',
    'updatetime' => '1482321548',
    'hitsid' => 'c-1-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '19',
    'typeid' => '0',
    'title' => '公安部决定启用电子往来台湾通行证 有效期10年',
    'style' => '',
    'thumb' => '',
    'keywords' => '公安部 台湾 有效期',
    'description' => '公安部决定启用电子往来台湾通行证　　福建省公安机关自12月26日起试点受理申请　　公安部近日发布公告，决定启用电子往来台湾通行证，福建   ',
    'posids' => '0',
    'url' => 'http://localhost/PC/index.php?m=content&c=index&a=show&catid=19&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1482321550',
    'updatetime' => '1482321571',
    'hitsid' => 'c-1-11',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  12 => 
  array (
    'id' => '12',
    'catid' => '19',
    'typeid' => '0',
    'title' => '煤炭为主的能源结构难以改变',
    'style' => '',
    'thumb' => '',
    'keywords' => '煤炭 能源 结构',
    'description' => '作为富煤资源的国家，煤炭主导了中国的能源结构模式。2015年的煤炭消费结构中，商品煤的消费量36 98亿吨，其中电力行业用煤18 39亿吨，钢铁   ',
    'posids' => '0',
    'url' => 'http://localhost/PC/index.php?m=content&c=index&a=show&catid=19&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1482321574',
    'updatetime' => '1482321601',
    'hitsid' => 'c-1-12',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  13 => 
  array (
    'id' => '13',
    'catid' => '19',
    'typeid' => '0',
    'title' => '胡军:哭戏将自己代入 有自知之明不演娘炮',
    'style' => '',
    'thumb' => '',
    'keywords' => '胡军 哭戏',
    'description' => '新浪娱乐讯 娱乐圈中人有标签者不少，小鲜肉、天仙、段子手、国民老公&hellip;&hellip;对于观众们来说，被标签者往往因为标签而更具辨识度。属于演员胡   ',
    'posids' => '0',
    'url' => 'http://localhost/PC/index.php?m=content&c=index&a=show&catid=19&id=13',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1482321603',
    'updatetime' => '1482321650',
    'hitsid' => 'c-1-13',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>